# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceInputItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemText', models.CharField(max_length=500)),
                ('isEditable', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='input_list',
            field=models.ManyToManyField(to='cw3.WorkspaceInputItem'),
        ),
    ]
