# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinputitem',
            name='itemText',
            field=models.TextField(),
        ),
    ]
