# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw3', '0002_auto_20170626_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinputitem',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
